version: 2.1

jobs:
  install_requirements:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - run: python --version
      - run:
          name: Install Python requirements
          command: |
            pip install -r requirements.txt    

  docker_build:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker
          docker_layer_caching: true
      - run:
          name: build docker image
          command: docker-compose up --build -d
      # - run:
      #     name: test image
      #     command: python


workflows:
  my-workflow:
    jobs:
      - install_requirements
      - docker_build
