version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - run:
          name: Install Python requirements
          command: |
            pip install -r requirements.txt
      - run: python --version
      - run:
          name: Start Docker Compose
          command: |
            docker-compose up -d

workflows:
  my-workflow:
    jobs:
      - build
