version: 2.1

jobs:
  install_requirements:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - run: python --version
      - run:
          name: Install Python requirements
          command: |
            pip install -r requirements.txt    

  docker_build:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: docker-compose up -d

  

workflows:
  my-workflow:
    jobs:
      - build
